using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace DoodleSharp.Execution;

/// <summary>
/// A syntax tree holding the one helper <see cref="AnimationNameRewriter"/> calls when a shape-typed
/// declaration is initialised by something other than <c>new</c>:
/// <c>VPoint vp1 = p1.AsVPoint();</c> runs as
/// <c>VPoint vp1 = global::__DoodleSharpShapeNaming.Name&lt;VPoint&gt;(p1.AsVPoint(), "vp1");</c>.
///
/// <para>
/// <b>Why a helper and not <c>{ Name = "x" }</c>.</b> An object initializer only exists on a
/// <c>new</c>. A method result has nowhere to hang one, so the name has to be set on the value as it
/// passes through — and only when it is empty, so a method that hands back an already-named shape
/// keeps that name.
/// </para>
///
/// <para>
/// <b>Why the type argument is spelled out.</b> It is copied from the declaration, so the call is
/// well-typed for every initializer the declaration itself accepts — <c>null</c>, <c>default</c>, a
/// target-typed conditional — none of which would let <c>T</c> be inferred.
/// </para>
///
/// <para>
/// <b>Why it is added only on the execute path.</b> The rewriter that calls it only runs there
/// (note 41), and keeping it out of the editor's compilation keeps it out of completion lists.
/// It is internal to the user's assembly and lives in the global namespace, so it cannot collide
/// with anything in <c>C2VGeometry</c> or <c>DoodleSharp.*</c>.
/// </para>
/// </summary>
internal static class ShapeNamingHelper
{
    /// <summary>The generated class, as the rewriter qualifies it.</summary>
    public const string ClassName = "__DoodleSharpShapeNaming";

    /// <summary>The path stamped on the tree — distinctive, like <see cref="SyntheticUsings.FilePath"/>.</summary>
    public const string FilePath = "DoodleSharp.ShapeNaming.g.cs";

    private const string Source = """
        // Generated by DoodleSharp. Not a file in your project.
        internal static class __DoodleSharpShapeNaming
        {
            public static T Name<T>(T value, string name)
            {
                if (value is global::C2VGeometry.Shape shape && string.IsNullOrEmpty(shape.Name))
                    shape.Name = name;
                return value;
            }
        }
        """;

    /// <summary>
    /// The tree, parsed once and shared. Built with an encoding for the same reason as
    /// <see cref="SyntheticUsings.Tree"/>: the execute path emits a PDB (CS8055 otherwise).
    /// </summary>
    public static SyntaxTree Tree { get; } = CSharpSyntaxTree.ParseText(
        Microsoft.CodeAnalysis.Text.SourceText.From(Source, System.Text.Encoding.UTF8),
        new CSharpParseOptions(LanguageVersion.Latest),
        path: FilePath);

    /// <summary>
    /// <c>global::__DoodleSharpShapeNaming.Name&lt;type&gt;(value, "name")</c>, carrying the value's
    /// own trivia on the outside so line numbers — and so stack traces — do not move.
    /// </summary>
    public static ExpressionSyntax Wrap(TypeSyntax type, ExpressionSyntax value, string name)
    {
        var method = SyntaxFactory.MemberAccessExpression(
            SyntaxKind.SimpleMemberAccessExpression,
            SyntaxFactory.AliasQualifiedName(
                SyntaxFactory.IdentifierName(SyntaxFactory.Token(SyntaxKind.GlobalKeyword)),
                SyntaxFactory.IdentifierName(ClassName)),
            SyntaxFactory.GenericName(
                SyntaxFactory.Identifier("Name"),
                SyntaxFactory.TypeArgumentList(
                    SyntaxFactory.SingletonSeparatedList(type.WithoutTrivia()))));

        var call = SyntaxFactory.InvocationExpression(
            method,
            SyntaxFactory.ArgumentList(SyntaxFactory.SeparatedList(new[]
            {
                SyntaxFactory.Argument(value.WithoutTrivia()),
                SyntaxFactory.Argument(SyntaxFactory.LiteralExpression(
                    SyntaxKind.StringLiteralExpression, SyntaxFactory.Literal(name))),
            })));

        return call.WithTriviaFrom(value);
    }
}
