using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace DoodleSharp.Execution;

/// <summary>
/// A syntax tree of nothing but <c>global using</c> directives, added to every compilation the app
/// builds — the same idiom as the SDK's generated <c>GlobalUsings.g.cs</c>.
///
/// <para>
/// It exists for one name. The viewport API is spelled <c>Viewports.Rows = 2</c> and
/// <c>Place(Viewports[0][1])</c>, which needs <c>Viewports</c> to be an <i>expression</i>: C# has no
/// static indexers (CS0720) and no namespace-level members, so a bare type name can never be
/// indexed. <c>C2VGeometry.ViewportRoot.Viewports</c> is a static property, and
/// <c>using static</c> brings it into scope unqualified.
/// </para>
///
/// <para>
/// <b>Why a synthetic tree and not a line in the project templates.</b> A template only covers the
/// files it generates, so a bare <c>Viewports</c> in a second, hand-written file would fail to
/// compile — for a core API that is a trap, not an inconvenience. Injecting it covers every file in
/// every project, including ones created before the feature existed.
/// </para>
///
/// <para>
/// <b>Why it is offset-safe.</b> It is a separate file with its own path, so it shifts nothing in
/// the user's own trees. That is what lets it ride on the offset-faithful editor path as well as the
/// execute path — the editor features that map caret offsets onto the compilation stay correct, and
/// IntelliSense resolves <c>Viewports</c> because the workspace carries the same tree.
/// </para>
/// </summary>
public static class SyntheticUsings
{
    /// <summary>
    /// The path stamped on the tree. Distinctive so that a diagnostic reported against it is
    /// obviously not the user's file, and so it cannot collide with a real source file.
    /// </summary>
    public const string FilePath = "DoodleSharp.GlobalUsings.g.cs";

    private const string Source = """
        // Generated by DoodleSharp. Not a file in your project.
        global using static C2VGeometry.ViewportRoot;
        """;

    /// <summary>
    /// The tree, parsed once. Syntax trees are immutable, so one instance is safely shared by every
    /// compilation and every thread.
    /// </summary>
    /// <remarks>
    /// The <see cref="System.Text.Encoding"/> is not decoration. The execute path emits a PDB, and
    /// Roslyn refuses to emit debug information for any tree whose <c>SourceText</c> has no encoding
    /// — "CS8055: Cannot emit debug information for a source text without encoding", reported
    /// against this file. Parsing from a bare string leaves the encoding null, so every tree that
    /// joins a compilation destined for emit has to be built this way, as the user's files already
    /// are.
    /// </remarks>
    public static SyntaxTree Tree { get; } = CSharpSyntaxTree.ParseText(
        Microsoft.CodeAnalysis.Text.SourceText.From(Source, System.Text.Encoding.UTF8),
        new CSharpParseOptions(LanguageVersion.Latest),
        path: FilePath);
}
